/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReadingRoomRouteImport } from './routes/_authenticated/reading-room'
import { Route as NovelsIndexRouteImport } from './routes/novels/index'
import { Route as NovelsSlugRouteImport } from './routes/novels/$slug'
import { Route as ReadersIndexRouteImport } from './routes/readers/index'
import { Route as ReadersHandleRouteImport } from './routes/readers/$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReadingRoomRoute =
  AuthenticatedReadingRoomRouteImport.update({
    id: '/reading-room',
    path: '/reading-room',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const NovelsIndexRoute = NovelsIndexRouteImport.update({
  id: '/novels/',
  path: '/novels/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsSlugRoute = NovelsSlugRouteImport.update({
  id: '/novels/$slug',
  path: '/novels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadersIndexRoute = ReadersIndexRouteImport.update({
  id: '/readers/',
  path: '/readers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadersHandleRoute = ReadersHandleRouteImport.update({
  id: '/readers/$handle',
  path: '/readers/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reading-room': typeof AuthenticatedReadingRoomRoute
  '/novels/$slug': typeof NovelsSlugRoute
  '/readers/$handle': typeof ReadersHandleRoute
  '/novels/': typeof NovelsIndexRoute
  '/readers/': typeof ReadersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reading-room': typeof AuthenticatedReadingRoomRoute
  '/novels/$slug': typeof NovelsSlugRoute
  '/readers/$handle': typeof ReadersHandleRoute
  '/novels': typeof NovelsIndexRoute
  '/readers': typeof ReadersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reading-room': typeof AuthenticatedReadingRoomRoute
  '/novels/$slug': typeof NovelsSlugRoute
  '/readers/$handle': typeof ReadersHandleRoute
  '/novels/': typeof NovelsIndexRoute
  '/readers/': typeof ReadersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/notifications'
    | '/profile'
    | '/reading-room'
    | '/novels/$slug'
    | '/readers/$handle'
    | '/novels/'
    | '/readers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/notifications'
    | '/profile'
    | '/reading-room'
    | '/novels/$slug'
    | '/readers/$handle'
    | '/novels'
    | '/readers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/reading-room'
    | '/novels/$slug'
    | '/readers/$handle'
    | '/novels/'
    | '/readers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  NovelsSlugRoute: typeof NovelsSlugRoute
  ReadersHandleRoute: typeof ReadersHandleRoute
  NovelsIndexRoute: typeof NovelsIndexRoute
  ReadersIndexRoute: typeof ReadersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reading-room': {
      id: '/_authenticated/reading-room'
      path: '/reading-room'
      fullPath: '/reading-room'
      preLoaderRoute: typeof AuthenticatedReadingRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/novels/': {
      id: '/novels/'
      path: '/novels'
      fullPath: '/novels/'
      preLoaderRoute: typeof NovelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels/$slug': {
      id: '/novels/$slug'
      path: '/novels/$slug'
      fullPath: '/novels/$slug'
      preLoaderRoute: typeof NovelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readers/': {
      id: '/readers/'
      path: '/readers'
      fullPath: '/readers/'
      preLoaderRoute: typeof ReadersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readers/$handle': {
      id: '/readers/$handle'
      path: '/readers/$handle'
      fullPath: '/readers/$handle'
      preLoaderRoute: typeof ReadersHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReadingRoomRoute: typeof AuthenticatedReadingRoomRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReadingRoomRoute: AuthenticatedReadingRoomRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  NovelsSlugRoute: NovelsSlugRoute,
  ReadersHandleRoute: ReadersHandleRoute,
  NovelsIndexRoute: NovelsIndexRoute,
  ReadersIndexRoute: ReadersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
